"""The cursive д, drawn here along a path taken from Lilex.

Generated by scripts/de_from_lilex.py -- edit that, not this.
Lilex is under the SIL Open Font License 1.1, which is what
lets it be an outline donor here. Held as data rather than read
from the donor at build time so the repository builds without a
font that lives outside it.

ONE contour plus o's own counter: the bowl is this face's o and
the arm is a stroke of this face's own weight grown out of its
right-hand wall, spliced so the wall carries on into it without
a seam. Nothing of the donor's own outline survives -- only the
line its arm travels along.

UN-SHEARED, like every outline a recipe sees. One entry per
master, in source order: contours of (x, y, type, smooth).
"""

DE = [
    # the donor's own Thin to Bold at +0.000
    [
        [
            (395.1, 458.3, 'offcurve', False),
            (340.5, 482.0, 'offcurve', False),
            (279.7, 482.0, 'curve', True),
            (134.7, 482.0, 'offcurve', False),
            (57.3, 351.0, 'offcurve', False),
            (100.5, 178.0, 'curve', True),
            (128.6, 65.0, 'offcurve', False),
            (218.3, -10.0, 'offcurve', False),
            (326.3, -10.0, 'curve', True),
            (461.3, -10.0, 'offcurve', False),
            (535.3, 109.3, 'offcurve', False),
            (505.9, 272.4, 'curve', True),
            (500.8, 300.7, 'offcurve', False),
            (494.5, 328.6, 'offcurve', False),
            (482.4, 354.3, 'curve', True),
            (461.5, 399.3, 'offcurve', False),
            (456.9, 451.1, 'offcurve', False),
            (433.7, 494.9, 'curve', True),
            (408.6, 542.1, 'offcurve', False),
            (374.2, 580.5, 'offcurve', False),
            (339.6, 610.6, 'curve', True),
            (303.0, 642.5, 'offcurve', False),
            (261.7, 666.6, 'offcurve', False),
            (218.1, 686.9, 'curve', True),
            (177.6, 705.7, 'offcurve', False),
            (136.8, 718.2, 'offcurve', False),
            (87.8, 730.6, 'curve', False),
            (82.0, 707.3, 'line', False),
            (130.2, 695.1, 'offcurve', False),
            (169.4, 682.8, 'offcurve', False),
            (207.9, 664.9, 'curve', True),
            (249.8, 645.4, 'offcurve', False),
            (288.9, 622.2, 'offcurve', False),
            (323.5, 592.1, 'curve', True),
            (356.4, 563.5, 'offcurve', False),
            (388.4, 527.3, 'offcurve', False),
            (411.8, 483.2, 'curve', True),
            (422.7, 462.6, 'offcurve', False),
            (429.4, 440.2, 'offcurve', False),
            (435.6, 417.5, 'curve', False),
        ],
    ],
    # the donor's own Thin to Bold at +0.000
    [
        [
            (296.9, 502.0, 'offcurve', False),
            (283.5, 503.0, 'offcurve', False),
            (270.0, 503.0, 'curve', True),
            (113.0, 503.0, 'offcurve', False),
            (26.7, 372.0, 'offcurve', False),
            (68.8, 203.0, 'curve', True),
            (107.7, 47.0, 'offcurve', False),
            (230.0, -10.0, 'offcurve', False),
            (330.0, -10.0, 'curve', True),
            (484.0, -10.0, 'offcurve', False),
            (573.5, 124.0, 'offcurve', False),
            (533.2, 286.0, 'curve', True),
            (532.4, 288.8, 'offcurve', False),
            (531.7, 291.7, 'offcurve', False),
            (530.9, 294.5, 'curve', True),
            (524.2, 318.6, 'offcurve', False),
            (521.9, 345.5, 'offcurve', False),
            (508.7, 373.0, 'curve', True),
            (485.8, 420.4, 'offcurve', False),
            (471.9, 471.9, 'offcurve', False),
            (447.9, 518.8, 'curve', True),
            (420.3, 572.7, 'offcurve', False),
            (378.4, 619.8, 'offcurve', False),
            (336.2, 656.5, 'curve', True),
            (294.5, 692.8, 'offcurve', False),
            (247.9, 719.4, 'offcurve', False),
            (200.2, 741.9, 'curve', True),
            (150.6, 765.2, 'offcurve', False),
            (101.9, 778.8, 'offcurve', False),
            (52.7, 791.2, 'curve', False),
            (22.9, 671.6, 'line', False),
            (68.4, 660.0, 'offcurve', False),
            (108.0, 647.4, 'offcurve', False),
            (147.1, 629.0, 'curve', True),
            (186.6, 610.4, 'offcurve', False),
            (222.1, 588.5, 'offcurve', False),
            (253.4, 561.3, 'curve', True),
            (274.5, 542.9, 'offcurve', False),
            (293.9, 521.9, 'offcurve', False),
            (309.9, 499.8, 'curve', False),
        ],
    ],
]
