"""The cursive д's hook, taken from Lilex and fitted here.

Generated by scripts/de_from_lilex.py -- edit that, not this.
Lilex is under the SIL Open Font License 1.1, which is what lets
it be an outline donor here. Held as data rather than read from
the donor at build time so the repository builds without a font
that lives outside it.

The BOWL is not here: it is this face's own o, added by the
recipe. Only the hook is the donor's, closed off across its own
root and left to overlap the bowl.

UN-SHEARED, like every outline a recipe sees. One entry per
master, in source order: contours of (x, y, type, smooth).
"""

DE = [
    # the donor's own Thin to Bold at +0.061
    [
        [
            (398.8, 456.6, 'offcurve', False),
            (342.6, 482.0, 'offcurve', False),
            (279.7, 482.0, 'curve', True),
            (134.7, 482.0, 'offcurve', False),
            (57.3, 351.0, 'offcurve', False),
            (100.5, 178.0, 'curve', True),
            (128.6, 65.0, 'offcurve', False),
            (218.3, -10.0, 'offcurve', False),
            (326.3, -10.0, 'curve', True),
            (469.3, -10.0, 'offcurve', False),
            (543.9, 124.0, 'offcurve', False),
            (499.5, 302.0, 'curve', True),
            (493.1, 327.7, 'offcurve', False),
            (477.7, 386.8, 'offcurve', False),
            (464.9, 407.9, 'curve', False),
            (430.7, 611.2, 'offcurve', False),
            (356.2, 701.9, 'offcurve', False),
            (194.8, 701.9, 'curve', True),
            (170.5, 701.9, 'offcurve', False),
            (146.8, 699.9, 'offcurve', False),
            (131.3, 697.7, 'curve', False),
            (125.4, 673.9, 'line', False),
            (150.2, 676.1, 'offcurve', False),
            (172.0, 678.2, 'offcurve', False),
            (196.9, 678.2, 'curve', True),
            (332.2, 678.2, 'offcurve', False),
            (403.6, 611.0, 'offcurve', False),
            (439.6, 413.3, 'curve', False),
        ],
    ],
    # the donor's own Thin to Bold at +0.977
    [
        [
            (324.6, 498.7, 'offcurve', False),
            (297.6, 503.0, 'offcurve', False),
            (270.0, 503.0, 'curve', True),
            (113.0, 503.0, 'offcurve', False),
            (26.7, 372.0, 'offcurve', False),
            (68.8, 203.0, 'curve', True),
            (107.7, 47.0, 'offcurve', False),
            (230.0, -10.0, 'offcurve', False),
            (330.0, -10.0, 'curve', True),
            (484.0, -10.0, 'offcurve', False),
            (573.5, 124.0, 'offcurve', False),
            (533.2, 286.0, 'curve', True),
            (524.1, 322.2, 'offcurve', False),
            (500.3, 433.3, 'offcurve', False),
            (481.3, 461.3, 'curve', False),
            (455.9, 633.3, 'offcurve', False),
            (372.0, 732.3, 'offcurve', False),
            (222.6, 732.3, 'curve', True),
            (188.6, 732.3, 'offcurve', False),
            (157.7, 727.5, 'offcurve', False),
            (133.4, 719.9, 'curve', False),
            (103.5, 599.8, 'line', False),
            (154.5, 607.5, 'offcurve', False),
            (181.8, 613.2, 'offcurve', False),
            (212.6, 613.2, 'curve', True),
            (285.3, 613.2, 'offcurve', False),
            (328.2, 575.3, 'offcurve', False),
            (350.1, 490.2, 'curve', False),
        ],
    ],
]
