"""The cursive г, taken whole from Lilex and fitted here.

Generated by scripts/ge_from_lilex.py -- edit that, not this.
Lilex is under the SIL Open Font License 1.1, which is what lets
it be an outline donor here. Held as data rather than read from
the donor at build time so the repository builds without a font
that lives outside it.

UN-SHEARED, like every outline a recipe sees: the italic goes
back on in build_cyrillic. Its height is this face's o, its width
0.97 of o's leaning, its terminals cut vertical and its stroke
solved to 0.98 of o's own wall.

One entry per master, in source order: contours of
(x, y, type, smooth). Both masters carry the same nodes in the
same order.
"""

GE = [
    # the donor's own Thin to Bold at +0.099
    [
        [
            (378.1, -10.0, 'offcurve', False),
            (447.7, 18.7, 'offcurve', False),
            (490.3, 79.9, 'curve', False),
            (494.9, 98.4, 'line', False),
            (428.4, 39.5, 'offcurve', False),
            (368.9, 15.4, 'offcurve', False),
            (294.7, 15.4, 'curve', True),
            (213.1, 15.4, 'offcurve', False),
            (168.6, 43.8, 'offcurve', False),
            (158.9, 106.3, 'curve', True),
            (146.4, 186.0, 'offcurve', False),
            (205.7, 216.5, 'offcurve', False),
            (270.6, 226.6, 'curve', True),
            (335.9, 236.8, 'line', False),
            (421.9, 250.2, 'offcurve', False),
            (479.4, 293.2, 'offcurve', False),
            (466.5, 376.2, 'curve', True),
            (454.5, 452.7, 'offcurve', False),
            (395.0, 482.0, 'offcurve', False),
            (316.8, 482.0, 'curve', True),
            (229.0, 482.0, 'offcurve', False),
            (174.2, 446.6, 'offcurve', False),
            (143.4, 407.7, 'curve', False),
            (138.8, 389.2, 'line', False),
            (192.6, 425.6, 'offcurve', False),
            (236.9, 456.6, 'offcurve', False),
            (318.5, 456.6, 'curve', True),
            (390.9, 456.6, 'offcurve', False),
            (430.3, 432.4, 'offcurve', False),
            (439.1, 375.7, 'curve', True),
            (450.5, 302.6, 'offcurve', False),
            (396.2, 272.3, 'offcurve', False),
            (327.9, 261.4, 'curve', True),
            (262.7, 251.2, 'line', False),
            (183.5, 238.6, 'offcurve', False),
            (116.9, 199.6, 'offcurve', False),
            (131.4, 106.6, 'curve', True),
            (144.2, 24.2, 'offcurve', False),
            (205.3, -10.0, 'offcurve', False),
            (295.6, -10.0, 'curve', True),
        ],
    ],
    # the donor's own Thin to Bold at +1.133
    [
        [
            (403.7, -10.0, 'offcurve', False),
            (467.0, 24.8, 'offcurve', False),
            (507.9, 71.0, 'curve', False),
            (528.1, 152.1, 'line', False),
            (399.3, 124.1, 'offcurve', False),
            (351.9, 104.9, 'offcurve', False),
            (308.2, 104.9, 'curve', True),
            (260.7, 104.9, 'offcurve', False),
            (244.1, 115.8, 'offcurve', False),
            (240.7, 137.8, 'curve', True),
            (237.9, 156.1, 'offcurve', False),
            (240.8, 172.1, 'offcurve', False),
            (300.8, 183.6, 'curve', True),
            (364.6, 196.2, 'line', False),
            (475.7, 218.1, 'offcurve', False),
            (509.8, 284.6, 'offcurve', False),
            (497.8, 362.3, 'curve', True),
            (484.3, 450.8, 'offcurve', False),
            (413.7, 503.0, 'offcurve', False),
            (305.8, 503.0, 'curve', True),
            (213.2, 503.0, 'offcurve', False),
            (156.8, 468.1, 'offcurve', False),
            (112.9, 419.6, 'curve', False),
            (92.7, 338.5, 'line', False),
            (222.1, 365.6, 'offcurve', False),
            (258.2, 388.1, 'offcurve', False),
            (305.8, 388.1, 'curve', True),
            (336.7, 388.1, 'offcurve', False),
            (355.9, 377.6, 'offcurve', False),
            (359.3, 355.8, 'curve', True),
            (362.2, 336.6, 'offcurve', False),
            (354.3, 322.7, 'offcurve', False),
            (298.7, 311.3, 'curve', True),
            (234.9, 298.7, 'line', False),
            (122.6, 277.7, 'offcurve', False),
            (90.1, 209.6, 'offcurve', False),
            (102.1, 131.2, 'curve', True),
            (115.9, 41.4, 'offcurve', False),
            (186.2, -10.0, 'offcurve', False),
            (308.3, -10.0, 'curve', True),
        ],
    ],
]
